// quizlet flash cards
let flashCards = `User Experience (UX)[Term/Def]A broad term that includes several disciplines that study the effect of design on the ease of use and level of satisfaction with a product, site or system.[New Question]User Experience Design (UXD)[Term/Def]Designing software products and systems to be useful to a set of end users. It is a broad concept applied during the design process. Covers the technical use of a product or service and its essential physical interface.[New Question]Customer Experience[Term/Def]The feelings of a customer generated by his or her interactions with a supplier's employees, systems, channels or products.[New Question]User Interface (UI), or Graphical User Interface (GUI)[Term/Def]What the user sees. This can be a set of commands or menus through which a user communicates with a program. It is also the space where interactions between humans and machines occurs.[New Question]Interaction Design (IXD)[Term/Def]The study of how a user interacts with a page, application or product. IXD facilitates the actions we want to take with any given system.[New Question]3-click Rule[Term/Def]The theory that users will abandon a website if they are unable to complete their task within 3 mouse clicks.[New Question]5-Second Test[Term/Def]A technique that involves showing users a single content page for a quick 5 seconds to gather their initial impressions. Users make important judgments in the first moments when they visit a page. It gives the team insight into essential information about the page.[New Question]F-Shaped Pattern[Term/Def]Users often read Web pages in an F-shaped pattered: two horizontal stripes, followed by by a vertical stripe. In a few seconds, thier eyes will move at amazing speed across your website's words in a one-of-a-kind pattern[New Question]Sketching[Term/Def]a drawing which designers use to propose. explore, refine and communicate ideas . As a UX designer, you too can use sketching as your first line of attack to crack a design problem[New Question]Wireframe[Term/Def]a simplified sketch of the information on a page. Also known as page architecture, page schematic, or a blueprint. It's a skeleton of the design and should contain all the important elements of the final product.[New Question]Mockup[Term/Def]A medium or highly detailed static representation of the design. A good mockup demonstrates the information structure, content and basic functionality in static form. Mockups make it easy to perceive the idea of the final product, and the process of mockup creation is less time-consuming compared to prototypes.[New Question]Prototype[Term/Def]Often confused with a wireframe, a prototype is a medium or a highly detailed representation of the final product. It simulates user interaction with the interface. It should allow the user to rate the content and interface and test the primary options for communication with the app. It may not look exactly like the final product, but it definitely should not be sketched in shades of gray. Interactions must be modeled in a way that closely mimic the final product.[New Question]80/20 Rule[Term/Def]20% of the functionality and features in any environment will be responsible for 80% of the actions taken within that environment. This is Pareto principle as applied to any website, web app or software environment.[New Question]A/B Testing[Term/Def]Determining which of two alternatives is preferred by the target audience.[New Question]Accessibility[Term/Def]The measure of a web page's usability by persons with one or more disabilities.[New Question]Golden Ratio[Term/Def]A mathematical ratio with origins in ancient Greece, also known as the Greek letter Phi. It is found in nature, and has made its way into graphic and print design as people deem it to be the most visually appealing layout to the human eye. approximately equals 1.618. We find it when we divide a line into two parts so that the full length divided by the long part is equal to the long part divided by the short part.[New Question]Grid[Term/Def]A system of horizontal and vertical lines providing a structural basis for page layout and design. It communicates order, economy and consistency. The grid provides a common structure and flexibility for organizing content.[New Question]Micro-copy[Term/Def]The ubiquitous text that turns up in tiny chunks on a webpage or in an application when you need it. It can be the label on a field, a quick set of instructions on what button to push, etc. It's the tiny text on which much of the product's UX hinges. Micro-copy provides those just-in-time clear instructions.[New Question]60-30-10 Rule[Term/Def]A timeless decorating rule that can help you put a color scheme together easily. Give balance to the colors used in any space.[New Question]Color Contrast[Term/Def]The difference between two colors. Black and white create the highest contrast possible. Colors can contrast in hue, value and saturation. You usually want a high contrast between text and its background color. But too high contrast between design elements might give an unsettled and messy impression. Effective use of contrast is the essential ingredient that makes the content accessible to every viewer.[New Question]Color Wheel[Term/Def]This circle shows the relationships between primary colors, secondary colors and tertiary colors. Artists and designers use red, yellow, and blue primaries arranged at three equally spaced points around their color wheel.[New Question]Brand Book[Term/Def]An official corporate document that explains the brand's identity and presents brand standards. Besides the design aspect, brand books may include a company overview and communication guidelines as well.[New Question]Corporate Identity Guideline[Term/Def]Defines how your company's brand, image and messaging are delivered to the public and particularly to your key audiences. positions the company, no matter how big or small. The rules for consistent typography, color use, and logo placement are all laid out in the corporate identity manual.[New Question]Web Analytics[Term/Def]The measurement, collection, and analysis of the internet to understand and optimize web usage.[New Question]Card Sorting Method[Term/Def]Understand how a typical user views a given set of items. Designers write items on individual paper cards, and then ask users to group together similar cards. Card sorting helps to create websites that are easy to navigate.[New Question]Gestalt Principles[Term/Def]People do not visually perceive items in isolation, but as part of a larger whole. These principles account for human tendencies towards similarity, proximity, continuity, and closure.[New Question]Dots Per Inch (DPI)[Term/Def]A way to measure the density of a print or video image. The number of differently colored dots that can fit into a one-inch space provides information about the resolution of an image. If an image is not of adequately high quality, it may not be able to be resized or printed without a loss of resolution.[New Question]Clickstream Analysis[Term/Def]A form of Web analytics.Tracking and analysis of visits to websites. This analysis reports user behavior such as routing, stickiness, where users come from and where they go from the site.[New Question]Minimum Viable Product (MVP)[Term/Def]A product with enough features to meet the needs of early customers. This strategy provides feedback for future product development.[New Question]Mindmap[Term/Def]A diagram used to visually organize information. A hierarchical and shows the relationships among the parts of the whole. It is often created around a single concept to which associated images, words and parts of words are added. Major ideas are connected directly to the central concept, and other ideas branch out from those.[New Question]Customer Journey Map (CJM)[Term/Def]A tool companies use to see what their customers truly want. A customer journey map tells the story from initial contact through to engagement and the long-term relationship. It may focus on a particular part of the story, or give an overview of the entire user experience. It talks about the user's feelings, motivations and questions for each of these touch points.[New Question]Onboarding[Term/Def]Designing a welcoming experience for new users by easing them into it. The design of the onboarding process for your site is usually limited to a first-time use scenario.[New Question]Data-driven[Term/Def]This means using all the available data: analytics, A/B tests, customer service logs and social media sentiment to develop a better understanding of UX. There are common misconceptions that user experience is purely an art. But there is a lot more involved. Understanding how to collect and process data is one of the key tasks you have to face as a UX designer.[New Question]Responsive Web Design (RWD)[Term/Def]provides an optimal viewing experience across platforms and devices. The content and layout of a website should efficiently adapt to the sizes and technical abilities of the device it is opened on.[New Question]Information Architecture (IA)[Term/Def]The organizing of information, including site hierarchies, web content, labeling schemes and navigation. IA makes it easy for people to find, understand and manage information.[New Question]Scalable Vector Graphics (SVG)[Term/Def]An imaging application and language written in XML. The interface offers a solution to the problem of sharing many sophisticated Web-based images and animations.[New Question]Vertical Rhythm[Term/Def]This concept originated from print typography. keeps the vertical spaces between elements on a page consistent with each other. This is often done with the help of a baseline - a common denominator used to create the consistent spaces.[New Question]User Scenarios[Term/Def]Hypothetical circumstances used to frame and prompt the user to follow or pursue a particular task path.[New Question]Heat Maps[Term/Def]Color-based representations of areas of interest/focus points; generally associated with eye-tracking software.[New Question]Breadcrumbs[Term/Def]are a navigation element that allows users to orient themselves within a Web site or move to one of the intermediate pages. are usually placed near the top of the page (generally, right under the browser's address bar). allow users to find their way to the homepage.[New Question]Call to Action (CTA)[Term/Def]For designers and content creators, is the word or phrase that stimulates users to interact with a product in the way it is designed for. elements are the interactive controls such as buttons, tabs, or links that enable users to perform the expected action.[New Question]Flat Design[Term/Def]A design philosophy based on simplicity and functionality. There are no techniques used to convey depth: no gradients, shadows, textures, and highlights that give a realistic view of the object. refers to the basics of graphics — bright colors, simple forms, buttons, and icons.[New Question]Landing Page[Term/Def]The Web page a given user goes to after clicking a link. Also known as the Target or Destination page.[New Question]Persona[Term/Def]The creation of a representative user based on available data and user interviews. Though the personal details of the persona may be fictional, the information used to create the user type is not.[New Question]White or Negative Space[Term/Def]The use of blank (unmarked) space on a page to promote content and navigation. When the products or pages have enough white space, it helps them feel uncluttered, elevates them, and makes them feel special. And it makes people want to take a closer look.[New Question]Context of Use Analysis[Term/Def]Observing users' behavior often helps create a website that supports their day-to-day activities. studies personas, user flows, wireframes, the content map, the site map, and the content strategy.[New Question]Conversion Rate[Term/Def]The percentage of visitors that complete a targeted transaction online.[New Question]Diary Study[Term/Def]A research method that involves providing participants with the materials and structure to record daily events, tasks and perceptions around a given subject in order to gain insight into their behavior and needs over time.[New Question]End Users[Term/Def]Refers to those people who use a website or those who are participants or subjects of research studies.[New Question]User Engagement[Term/Def]It represents the purposeful choices a user makes with website content. is how people get value from the site.[New Question]Eye Tracking[Term/Def]Specialized hardware and software that tracks users' point of vision on an interface. It tracks where users focus their visual attention while viewing an interface.[New Question]Fishbone Diagram[Term/Def]A diagram designed to identify cause-and-effect relationships between factors in a given situation. It is made up of a "head", which states a problem, and bones along the spine that represent factors and categories of factors.[New Question]User-Centered Design (UCD)[Term/Def]An approach to designing a product or service (user interface design), in which the end user is placed in the center of the process.[New Question]Fitts' Law[Term/Def]A mathematical model that predicts how long it will take to point at a target based on the target's size and proximity. The further away and smaller it is, the longer it will take for users to interact with it.[New Question]Focus Group[Term/Def]A focus group is a pointed discussion with a group of participants led by a moderator. Questions are designed to gather feedback about users, products, concepts, prototypes, tasks, and strategies.[New Question]Inductive UI[Term/Def]explain each task step with a clear and concise main instruction that answers the first question users have[New Question]Common types of UX jobs[Term/Def]in-house, consultancy, contractor, and freelance[New Question]Tone[Term/Def]attitude UI conveys to the users`;

// DOM stuff
const quizletCardDOM = document.getElementById('quizletCard');
const quizletQDOM = document.getElementById('quizletQ');
const quizletADOM = document.getElementById('quizletA');
const quizletBtnDOM = document.getElementById('quizletBtn');
const homePageDOM = document.getElementById('homePage');
const searchBarDOM = document.getElementById('searchBar');
const audioDOM = document.getElementById('ambientMusic')
const volumeSliderDOM = document.getElementById('volumeSlider');
const musicToggleDOM = document.getElementById('musicToggle');

// from stack overflow, for shuffle
//https://stackoverflow.com/questions/2450954/how-to-randomize-shuffle-a-javascript-array
function shuffle(array) {
  let currentIndex = array.length,  randomIndex;

  // While there remain elements to shuffle...
  while (currentIndex != 0) {

    // Pick a remaining element...
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;

    // And swap it with the current element.
    [array[currentIndex], array[randomIndex]] = [
      array[randomIndex], array[currentIndex]];
  }

  return array;
}

// music stuff
let playlist = ["Sono Chi No Sadame", "Bloody Stream", "Jotaro's Theme", "Kira's Theme", "Giorno's Theme", "Jolyne's Theme"];
playlist.forEach((song, index) => {
    playlist[index] = {
        title: song,
        //audio: new Audio(`./assets/ambient${index+1}.mp3`)
        audio: `./assets/ambient${index+1}.mp3`
    }
});
playlist = shuffle(playlist);

let currSong = 0;

const prevSong = () => {
    if(audioDOM.currentTime <= 3) {
        if(currSong > 0){
            currSong--;
        } else {
            currSong = playlist.length-1;
        }
        audioDOM.src = playlist[currSong].audio;
        $('#songTitle').html(playlist[currSong].title);
    } else {
        audioDOM.currentTime = 0;
    }
}

const nextSong = () => {
    if(currSong < playlist.length-1){
        currSong++;
    } else {
        currSong = 0;
    }
    audioDOM.src = playlist[currSong].audio;
    $('#songTitle').html(playlist[currSong].title);
};

const changeVolume = (value) => {
    audioDOM.volume = value / 100;
};

musicToggleDOM.addEventListener('mousedown', () => {
    if(!audioDOM.paused) {
        audioDOM.pause();
        musicToggleDOM.classList.remove('fa-pause');
        musicToggleDOM.classList.add('fa-play');
    } else {
        audioDOM.play();
        musicToggleDOM.classList.remove('fa-play');
        musicToggleDOM.classList.add('fa-pause');
    }
});


// stolen from a project last year, does the typing into divs
function printLetterByLetter(destination, message, speed){
    var i = 0;
    var interval = setInterval(function(){
        $("#"+destination).html(message.substring(0,i));
        i++;
        if (i > message.length){
            clearInterval(interval);
        }
    }, speed);
}

// code for flashcard at beginning
flashCards = flashCards.split('[New Question]');

for(let i = 0; i < flashCards.length; i++) {
    flashCards[i] = flashCards[i].split('[Term/Def]');
}

let quizletQ = flashCards[Math.floor(Math.random() * flashCards.length)];
quizletQDOM.innerHTML = quizletQ[0];

let answerShowing = false;
const showQAnswer = () => {
    if(!answerShowing) {
        quizletADOM.style.display = 'block';
        quizletBtnDOM.textContent = 'Proceed to new tab';
        printLetterByLetter('quizletA', quizletQ[1], 2500/quizletQ[1].length);
        answerShowing = true;
    } else {
        quizletCardDOM.style.display = 'none';
        homePageDOM.style.display = 'flex';
        audioDOM.src = playlist[0].audio;
        $('#songTitle').html(playlist[0].title);
        $('#ambientMusic').on('ended', () => {
            nextSong();
        })
        setTimeout(() => {
            searchBarDOM.focus();
        }, 100);
        // reveals the secret to the fun fact
        setTimeout(() => {
            for(let i = 0; i < searchBarDOM.placeholder.length; i++){
                setTimeout(() => {
                    searchBarDOM.placeholder = searchBarDOM.placeholder.substring(0, searchBarDOM.placeholder.length - 1);
                }, 100 * i);
            }
        }, 10000);
        setTimeout(() => {
            const secrets = [
                'Click the logo for a fun fact :)',
                'Like the music?',
                'How is your day going?',
                'We will make it through today together!',
                'Did the flashcard stump you?'
            ];
            const secret = secrets[Math.floor(Math.random() * (secrets.length))];
            for(let i = 0; i < secret.length; i++){
                setTimeout(() => {
                    searchBarDOM.placeholder += secret[i];
                }, 100 * i);
            }
        }, 10000 + 100 * searchBarDOM.placeholder.length);
    }
}

// puts the random number fact on screen in logo is clicked
let fact = '';
let revealed = false;
$('#header').on('click', () => {
    if(!revealed){
        $('#header img').css({
            "animation": "0.5s ease-out 0s 1 flickerIn",
            "animation-fill-mode": "forwards"
        }).delay(1000).queue(() => {
            $('#header').delay(1000).html(`<div id="numFact"><img src="./assets/me.png" alt="me"><p id='fact'></p></div>`);
            printLetterByLetter('fact', fact, 2500/fact.length);
            revealed = true;
        });
    } else {
        printLetterByLetter('fact', 'Hey! You only get one fact per tab!', 2500/fact.length);
        $('#header').off()
    }
});

// Gets the random number fact
var options = {
  method: 'GET',
  url: 'https://numbersapi.p.rapidapi.com/random/trivia',
  params: {min: '1', max: '1000', fragment: 'true', json: 'true'},
  headers: {
    'x-rapidapi-host': 'numbersapi.p.rapidapi.com',
    'x-rapidapi-key': 'aae51eccebmshac18a8f2e468d43p154b63jsn4147fd2b418e'
  }
};

axios.request(options).then(function (response) {
	const { text, number } = response.data;
    fact = `Stick me says: ${number} is ${text}`;

}).catch(function (error) {
	console.error(error);
});